# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_key', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[(b'', b''), (b'Draft', b'Draft'), (b'Trash', b'Trash'), (b'Published', b'Published')], default=b'Draft', max_length=200)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('post_type', models.CharField(choices=[(b'', b''), (b'Blog', b'Blog'), (b'News', b'News')], default=b'Blog', max_length=200)),
                ('excerpt', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'blogs',
            },
        ),
    ]
