# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20170612_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsers',
            old_name='event_id',
            new_name='event',
        ),
    ]
