# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20170612_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnewsletter',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
